site_name: Análise de Sentimentos e Tópicos Recorrentes do Brasil Participativo

# Configurações de navegação
nav:
  - Quem Somos: index.md
  - Visão Geral: overview.md
  - Requisitos:
      - Funcionais: requirements/functional.md
      - Não Funcionais: requirements/nonfunctional.md
  - Arquitetura:
      - Visão Geral: architecture/architecture.md
  - Uso:
      - Guia do Usuário: usage/userguide.md
      - FAQs: usage/faqs.md

theme:
  # Trata-se de um tema personalizado, que foi desenvolvido a partir do tema Material
  name: material

  # Configurações de features - elementos que podem ser adicionados a documentação
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.full
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  # Configurações de idioma
  language: pt

  # Configurações de cores e fontes
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono

# Configurações de texto no rodapé
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/unb-mds/2024-2-Squad05
